contact form section for mobile view portfolio project
okemboi/portfolio pull request #3
Opened 2023-04-05 15:03 UTC by okemboi

I added html for contact-form with below sections

- Full name 
- Email 
- Message box
- Form spree to send collected data after submitting the form

2023-04-05 15:10 UTC, levy002 reviewed
## Hello @okemboi & @rabayarabu 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that have be done in pair programing. I can see your partner's commits but I can not identify any commits of Mr @okemboi and as you know in order to be sure that everyone has contributed to the projects, we mus see every partner's commits. Kindly contribute to your project and submit it again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-05 16:54 UTC, frank1738 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 16:54 UTC, frank1738 commented on index.html
> +    </section>
- Your contact form is not styled at all. Kindly style it to match the original design.

![image](https://user-images.githubusercontent.com/98453979/230149592-46e37534-de6f-4d1a-94d2-f0ccebb214c0.png)

### Checkout the original design

![image](https://user-images.githubusercontent.com/98453979/230149880-d1647b39-149c-4f9d-a694-5cf7d5e3b554.png)

2023-04-05 20:54 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @okemboi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 20:54 UTC, Qoosim commented on index.html
> +    </section>
- [ ] Great job implementing the changes required by the previous reviewer. However, there're few things you need to improve on this milestone. It is required to stick to the figma design as close as possbile. This includes font, color, spacing among others. Your design doesn't yet look like that of figma. Kindly give a closer look and try to produce a replica of figma design.

- [ ] Also, at this moment, all the footer icons are not showing. Kindly attend to that too.

### Your Design
![your-form](https://user-images.githubusercontent.com/26597432/230209042-f0a9d041-cb6e-4eb3-9b37-d801dccb6081.png)

### Figma Design
![figma-form](https://user-images.githubusercontent.com/26597432/230209080-730dd97e-0093-4b1e-bc5f-288bb252e859.png)

2023-04-06 11:31 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @okemboi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 11:39 UTC, merged